const { sendMail } = require('./emailService')

/**
 * Email templates for password reset and OTP
 * Using existing email service (Gmail SMTP) as Firebase Admin SDK
 * doesn't provide direct custom email template support
 */

/**
 * Send password reset email with secure token link
 * @param {string} email - User's email address
 * @param {string} resetToken - Secure reset token generated by backend
 * @param {string} userName - User's name for personalization
 * @returns {Promise<void>}
 */
async function sendPasswordResetEmail(email, resetToken, userName = 'User') {
  try {
    const resetUrl = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/reset-password?token=${resetToken}`
    
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .container {
            background: #ffffff;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          }
          .logo {
            text-align: center;
            font-size: 32px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 30px;
          }
          h1 {
            color: #1f2937;
            font-size: 24px;
            margin-bottom: 20px;
          }
          .button {
            display: inline-block;
            background: #2563eb;
            color: #ffffff !important;
            padding: 14px 32px;
            text-decoration: none;
            border-radius: 6px;
            font-weight: 600;
            margin: 20px 0;
          }
          .button:hover {
            background: #1d4ed8;
          }
          .warning {
            background: #fef3c7;
            border-left: 4px solid #f59e0b;
            padding: 12px;
            margin: 20px 0;
            border-radius: 4px;
          }
          .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            font-size: 14px;
            color: #6b7280;
          }
          .expiry {
            font-weight: 600;
            color: #dc2626;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="logo">KARC</div>
          
          <h1>Reset Your Password</h1>
          
          <p>Hi ${userName},</p>
          
          <p>We received a request to reset your password. Click the button below to create a new password:</p>
          
          <div style="text-align: center;">
            <a href="${resetUrl}" class="button">Reset Password</a>
          </div>
          
          <div class="warning">
            <strong>⏰ Important:</strong> This link will expire in <span class="expiry">15 minutes</span> for security reasons.
          </div>
          
          <p>If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.</p>
          
          <p>For security, this link can only be used once.</p>
          
          <div class="footer">
            <p><strong>Link not working?</strong> Copy and paste this URL into your browser:</p>
            <p style="word-break: break-all; color: #2563eb;">${resetUrl}</p>
            
            <p style="margin-top: 20px;">
              Best regards,<br>
              The KARC Team
            </p>
          </div>
        </div>
      </body>
      </html>
    `
    
    await sendMail({
      to: email,
      subject: 'Reset Your Password - KARC',
      html,
    })
    
    console.log(`[Email] Password reset email sent to ${email}`)
    return { success: true }
  } catch (error) {
    console.error('[Email] Failed to send password reset:', error.message)
    throw new Error('Failed to send password reset email')
  }
}

/**
 * Send OTP email for passwordless login
 * @param {string} email - User's email address
 * @param {string} otp - 6-digit OTP
 * @param {string} userName - User's name for personalization
 * @returns {Promise<void>}
 */
async function sendOtpEmail(email, otp, userName = 'User') {
  try {
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .container {
            background: #ffffff;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          }
          .logo {
            text-align: center;
            font-size: 32px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 30px;
          }
          h1 {
            color: #1f2937;
            font-size: 24px;
            margin-bottom: 20px;
          }
          .otp-box {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #ffffff;
            font-size: 42px;
            font-weight: bold;
            letter-spacing: 8px;
            text-align: center;
            padding: 30px;
            border-radius: 12px;
            margin: 30px 0;
            font-family: 'Courier New', monospace;
          }
          .warning {
            background: #fef3c7;
            border-left: 4px solid #f59e0b;
            padding: 12px;
            margin: 20px 0;
            border-radius: 4px;
          }
          .security-notice {
            background: #fee2e2;
            border-left: 4px solid #dc2626;
            padding: 12px;
            margin: 20px 0;
            border-radius: 4px;
          }
          .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            font-size: 14px;
            color: #6b7280;
          }
          .expiry {
            font-weight: 600;
            color: #dc2626;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="logo">KARC</div>
          
          <h1>Your Login Code</h1>
          
          <p>Hi ${userName},</p>
          
          <p>Use this one-time code to log in to your account:</p>
          
          <div class="otp-box">${otp}</div>
          
          <div class="warning">
            <strong>⏰ Time Sensitive:</strong> This code will expire in <span class="expiry">5 minutes</span>.
          </div>
          
          <div class="security-notice">
            <strong>🔒 Security Alert:</strong> If you didn't request this code, please ignore this email. Someone may have entered your email address by mistake.
          </div>
          
          <p><strong>Note:</strong> This code can only be used once and will become invalid after use or expiry.</p>
          
          <div class="footer">
            <p style="margin-top: 20px;">
              Best regards,<br>
              The KARC Team
            </p>
            
            <p style="margin-top: 20px; font-size: 12px;">
              Never share this code with anyone. KARC will never ask for your OTP via phone or email.
            </p>
          </div>
        </div>
      </body>
      </html>
    `
    
    await sendMail({
      to: email,
      subject: `${otp} is your KARC login code`,
      html,
    })
    
    console.log(`[Email] OTP email sent to ${email}`)
    return { success: true }
  } catch (error) {
    console.error('[Email] Failed to send OTP:', error.message)
    throw new Error('Failed to send OTP email')
  }
}

module.exports = {
  sendPasswordResetEmail,
  sendOtpEmail,
}

